### ISSUE TITLE
'SameSite' is not defined in http.Cookie

### ISSUE THREAD

**Issue by sedited** [fiatjaf/sparko#1]
Currently go version 1.10.2 throws an error when compiling:

    ./auth.go:48:15: unknown field 'SameSite' in struct literal of type http.Cookie

According to the [securecookie docs](https://github.com/gorilla/securecookie) SameSite is not part of the http.Cookie struct. Removing it from the struct makes the build pass.

**Comment by fiatjaf** [comment]
Can you please try to upgrade your Go installation and try again?

I'm using `go1.11.5` and I have the `SameSite` field. See here: https://golang.org/pkg/net/http/#Cookie
