### ISSUE TITLE
unable to save the lnurl-pay static qrcode in tip.bigsun.xyz  

### ISSUE THREAD

**Issue by bitcoind-me** [fiatjaf/sparko#14]
Hi, when I press save in the tip.bigsun.xyz to create a static qr code for lnurl-pay, my c-lightning node throws
<pre>
UNUSUAL lightningd: invoice: insufficient incoming capacity for 1000msat 
</pre>

any suggestion?

 * c-lightning: v0.10.0
 * sparko: v2.7
 * tls certs: letsencrypt

**Comment by fiatjaf** [comment]
tip.bigsun.xyz is trying to create an invoice to test the connection. Is your node not able to create an invoice? I think it should be even with that warning.

Or maybe that's the tip.bigsun.xyz database acting up again.

**Comment by bitcoind-me** [comment]
The error had to do with the inbound liquidity, after providing that, I could receive payments and the error is gone. But clicking save on tip.bigsun.xyz throws this error on the site itself:

<pre>
Couldn't save: failed to save: %!w(*tls.permamentError=&{0xc0003d4000})
</pre>

No error or warning shows up on the lightningd logs after clicking save.

So I can create invoices and receive payments on my node. Also sparko web wallet works with no problem. The https bindings seems to work since I can see my node is listening on the port 443.

Don't know what is actually causing this problem.

**Comment by fiatjaf** [comment]
Please try now, I think the tip.bigsun.xyz database was borked. Sorry about that, very amateurish service.

**Comment by bitcoind-me** [comment]
It worked. thank you.
