### ISSUE TITLE
Unable to turn off sparko or upgrade

### ISSUE THREAD

**Issue by heyambob** [fiatjaf/sparko#17]
It's very strange. I'm running c-ln with sparko. I have it on the config file. Now I tried to comment the line that load sparko out, but it's still loading.

```
#plugin=/LN/sparko_linux_amd64
```

I want to upgrade to 2.9, so I have the line point to the new binary, yet it's still saying 2.8.
Looks like it does not care about the line on the config, and has fused itself into my c-lightning node

**Comment by fiatjaf** [comment]
c-lightning automatically loads any executable in the `$LN_PATH/plugins` directory (and some other magical paths) regardless of your config.

**Comment by heyambob** [comment]
You are right, I put sparko in the plugins directory, although, I tried to replace the 2.8 with 2.9 sparko_linux_amd64 binary, it's stil saying "plugin-sparko  initialized plugin v2.8" . My guess is you forgot to change the version number on the greeting.

**Comment by fiatjaf** [comment]
You are right in your guess. Sorry about that.
