### ISSUE TITLE
Build fails at 0a8a250

### ISSUE THREAD

**Issue by hkjn** [fiatjaf/sparko#2]
I'm hitting a compilation error trying to build from 0a8a250:
```
$ go version
go version go1.11.6 linux/amd64
$ make
go-bindata -tags full -prefix node_modules/spark-wallet/dist/www -o bindata.go node_modules/spark-wallet/dist/www/...
go build -tags full -o ./sparko -ldflags "-X main.Version=$(jq -r .version node_modules/spark-wallet/package.json)"
# github.com/fiatjaf/sparko
./rpc.go:94:21: cmderr.Msg undefined (type lightning.ErrorCommand has no field or method Msg)
make: *** [Makefile:5: prod] Error 2
```

It seems that as of commit `69be6ffc` for `github.com/fiatjaf/lightningd-gjson-rpc`, there is indeed no `Msg` field defined in `lightning.ErrorCommand`:

* https://github.com/fiatjaf/lightningd-gjson-rpc/blob/master/error.go#L10

[Commenting out L94](https://github.com/fiatjaf/sparko/compare/master...hkjn:20190509-demo-issue?expand=1) makes the build succeed:

```
$ make
go-bindata -tags full -prefix node_modules/spark-wallet/dist/www -o bindata.go node_modules/spark-wallet/dist/www/...
go build -tags full -o ./sparko -ldflags "-X main.Version=$(jq -r .version node_modules/spark-wallet/package.json)"
$ file sparko
sparko: ELF 64-bit LSB executable, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, Go BuildID=sWssIfhXdBUUvX6mSgyb/JlwmhngRmixF17udVZM9/-0PRnYyOK8HraPrJ48JV/rslXeyCsbZZbmu3Is1Ct, not stripped
```

**Comment by fiatjaf** [comment]
Oops, sorry about that. I did bad stuff on that other repo.
That's why we need better dependency management in Go, but I'm still dreaming they will come up with something better than `go mod` stuff.

**Comment by ghost** [comment]
typing `go get github.com/fiatjaf/sparko` as described in the readme yields in a similar error:
````
# github.com/fiatjaf/sparko
go/pkg/mod/github.com/fiatjaf/sparko@v0.2.1/rpc.go:94:21: cmderr.Msg undefined (type lightning.ErrorCommand has no field or method Msg)
````
